

export const HEADING_CHANGE = 'HEADING_CHANGE'

export const NEW_COMMENT = 'NEW_COMMENT'
export const NEW_COMMENT_FAILED = 'NEW_COMMENT_FAILED'

export const LOAD_DISHES = 'LOAD_DISHES'
export const DISHES_LOADING = 'DISHES_LOADING'
export const DISH_FAILED = 'DISH_FAILED'

export const LOAD_COMMENTS = 'LOAD_COMMENTS'
export const COMMENT_LOADING = 'COMMENT_LOADING'
export const COMMENT_LOADING_FAILED = 'COMMENT_LOADING_FAILED'
export const SELECTED_COMMENT = 'SELECTED_COMMENT'

