

export const HEADING_CHANGE = 'HEADING_CHANGE'

export const NEW_COMMENT = 'NEW_COMMENT'

export const LOAD_DISHES = 'LOAD_DISHES'
export const DISHES_LOADING = 'DISHES_LOADING'

export const LOAD_COMMENTS = 'LOAD_COMMENTS'
export const COMMENT_LOADING = 'COMMENT_LOADING'

